In [1]:
# Installation automatique des dépendances requises dans le noyau Jupyter actuel
%pip install -r ../requirements.txt

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 3)) (2.4.6)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 6)) (1.8.0)
Requirement already satisfied: matplotlib>=3.7.0 in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 9)) (3.10.9)
Requirement already satisfied: seaborn>=0.12.0 in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 10)) (0.13.2)
Requirement already satisfied: plotnine>=0.12.0 in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 11)) (0.15.4)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 14)) (7.2.0)
Requirement already satisfied: jupyter in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 15)) (1.1.1)
Requirement already satisfied: quarto in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 16)) (0.1.0)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/site-packages (from -r ../requirements.txt (line 19)) (1.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/site-packages (from pandas>=2.0.0->-r ../requirements.txt (line 2)) (2.9.0.post0)

Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/site-packages (from scikit-learn>=1.2.0->-r ../requirements.txt (line 6)) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/site-packages (from scikit-learn>=1.2.0->-r ../requirements.txt (line 6)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/site-packages (from scikit-learn>=1.2.0->-r ../requirements.txt (line 6)) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/site-packages (from matplotlib>=3.7.0->-r ../requirements.txt (line 9)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/site-packages (from matplotlib>=3.7.0->-r ../requirements.txt (line 9)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/site-packages (from matplotlib>=3.7.0->-r ../requirements.txt (line 9)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/site-packages (from matplotlib>=3.7.0->-r ../requirements.txt (line 9)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/site-packages (from matplotlib>=3.7.0->-r ../requirements.txt (line 9)) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/site-packages (from matplotlib>=3.7.0->-r ../requirements.txt (line 9)) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.12/site-packages (from matplotlib>=3.7.0->-r ../requirements.txt (line 9)) (3.3.2)
Requirement already satisfied: mizani~=0.14.0 in /usr/local/lib/python3.12/site-packages (from plotnine>=0.12.0->-r ../requirements.txt (line 11)) (0.14.4)
Requirement already satisfied: statsmodels>=0.14.6 in /usr/local/lib/python3.12/site-packages (from plotnine>=0.12.0->-r ../requirements.txt (line 11)) (0.14.6)
Requirement already satisfied: comm>=0.1.1 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (0.2.3)

Requirement already satisfied: debugpy>=1.6.5 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (9.13.0)
Requirement already satisfied: jupyter-client>=8.8.0 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (0.2.2)
Requirement already satisfied: nest-asyncio>=1.4 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (1.6.0)
Requirement already satisfied: psutil>=5.7 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (7.2.2)
Requirement already satisfied: pyzmq>=25 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in /usr/local/lib/python3.12/site-packages (from ipykernel->-r ../requirements.txt (line 14)) (5.15.0)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/site-packages (from jupyter->-r ../requirements.txt (line 15)) (7.5.6)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.12/site-packages (from jupyter->-r ../requirements.txt (line 15)) (6.6.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.12/site-packages (from jupyter->-r ../requirements.txt (line 15)) (7.17.1)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/site-packages (from jupyter->-r ../requirements.txt (line 15)) (8.1.8)
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.12/site-packages (from jupyter->-r ../requirements.txt (line 15)) (4.5.7)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/site-packages (from quarto->-r ../requirements.txt (line 16)) (5.10.4)
Requirement already satisfied: nbclient in /usr/local/lib/python3.12/site-packages (from quarto->-r ../requirements.txt (line 16)) (0.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/site-packages (from quarto->-r ../requirements.txt (line 16)) (6.0.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.12/site-packages (from kagglehub->-r ../requirements.txt (line 19)) (0.1.23)
Requirement already satisfied: requests in /usr/local/lib/python3.12/site-packages (from kagglehub->-r ../requirements.txt (line 19)) (2.34.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/site-packages (from kagglehub->-r ../requirements.txt (line 19)) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub->-r ../requirements.txt (line 19)) (7.35.0)
Requirement already satisfied: decorator>=5.1.0 in /usr/local/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /usr/local/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /usr/local/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (0.20.0)
Requirement already satisfied: pexpect>4.6 in /usr/local/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in /usr/local/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /usr/local/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (0.6.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (0.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (0.8.7)

Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->-r ../requirements.txt (line 14)) (4.9.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/site-packages (from pexpect>4.6->ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (0.7.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->-r ../requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (3.0.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->-r ../requirements.txt (line 14)) (0.2.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/site-packages (from statsmodels>=0.14.6->plotnine>=0.12.0->-r ../requirements.txt (line 11)) (1.0.2)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/lib/python3.12/site-packages (from ipywidgets->jupyter->-r ../requirements.txt (line 15)) (4.0.15)

Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/lib/python3.12/site-packages (from ipywidgets->jupyter->-r ../requirements.txt (line 15)) (3.0.16)
Requirement already satisfied: async-lru>=1.0.0 in /usr/local/lib/python3.12/site-packages (from jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/site-packages (from jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.12/site-packages (from jupyterlab->jupyter->-r ../requirements.txt (line 15)) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /usr/local/lib/python3.12/site-packages (from jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /usr/local/lib/python3.12/site-packages (from jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2.18.2)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /usr/local/lib/python3.12/site-packages (from jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.12/site-packages (from jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in /usr/local/lib/python3.12/site-packages (from jupyterlab->jupyter->-r ../requirements.txt (line 15)) (82.0.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in /usr/local/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in /usr/local/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.5.4)
Requirement already satisfied: prometheus-client>=0.9 in /usr/local/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.25.0)
Requirement already satisfied: send2trash>=1.8.2 in /usr/local/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (1.9.0)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.14.0)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.12/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (4.26.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (4.15.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/site-packages (from jinja2>=3.0.3->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (3.0.3)

Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.30.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (4.1.0)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (25.10.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/site-packages (from nbconvert->jupyter->-r ../requirements.txt (line 15)) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter->-r ../requirements.txt (line 15)) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/site-packages (from nbconvert->jupyter->-r ../requirements.txt (line 15)) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/site-packages (from nbconvert->jupyter->-r ../requirements.txt (line 15)) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/site-packages (from nbconvert->jupyter->-r ../requirements.txt (line 15)) (3.2.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/site-packages (from nbconvert->jupyter->-r ../requirements.txt (line 15)) (1.5.1)

Requirement already satisfied: webencodings in /usr/local/lib/python3.12/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter->-r ../requirements.txt (line 15)) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter->-r ../requirements.txt (line 15)) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/site-packages (from nbformat->quarto->-r ../requirements.txt (line 16)) (2.21.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests->kagglehub->-r ../requirements.txt (line 19)) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/site-packages (from requests->kagglehub->-r ../requirements.txt (line 19)) (2.7.0)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.12/site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (1.3.1)

Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in /usr/local/lib/python3.12/site-packages (from beautifulsoup4->nbconvert->jupyter->-r ../requirements.txt (line 15)) (2.8.3)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.12/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (1.4.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->-r ../requirements.txt (line 15)) (2026.2)

Note: you may need to restart the kernel to use updated packages.

# 📥 Étape 1 : Acquisition des Données & Multi-Sources (Squelette Étudiant)

Cette étape correspond au premier chapitre du pipeline de Data Science. L'objectif est d'identifier, d'importer et de consolider vos jeux de données bruts issus de différentes sources (fichiers CSV locaux, requêtes API, bases de données, etc.).

### 1. Initialisation de l'environnement

In [2]:
import os
import sys
import pandas as pd
import numpy as np

# Ajout du dossier parent au chemin de recherche des modules
sys.path.append(os.path.abspath('..'))

print("Libraries importées avec succès ! Prêt pour l'étape d'Acquisition des Données.")

Libraries importées avec succès ! Prêt pour l'étape d'Acquisition des Données.

### 2. Chargement de la source de données principale

Chargement du jeu de données **Automobile** depuis le fichier CSV local `data/raw/Automobile.csv`.

In [3]:
# Chemin vers le jeu de données principal
main_data_path = '../data/raw/Automobile.csv'

# Chargement du dataset avec Pandas
df_main = pd.read_csv(main_data_path)

# Affichage de la taille et des premières lignes
print(f"Dimensions du dataset principal : {df_main.shape}")
df_main.head()

Dimensions du dataset principal : (398, 9)

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa

### 3. Intégration de données secondaires (Multi-Sources)

Création d'un DataFrame complémentaire contenant des informations géographiques sur l'origine des véhicules (région et code continent).

In [4]:
# Création d'un DataFrame secondaire avec les informations géographiques par origine
origin_info = pd.DataFrame({
    'origin': ['usa', 'europe', 'japan'],
    'region': ['Amérique du Nord', 'Europe', 'Asie'],
    'continent_code': ['NA', 'EU', 'AS']
})

print(f"Dimensions des données secondaires : {origin_info.shape}")
print("Données secondaires prêtes :")
origin_info.head()

Dimensions des données secondaires : (3, 3)
Données secondaires prêtes :

   origin            region continent_code
0     usa  Amérique du Nord             NA
1  europe            Europe             EU
2   japan              Asie             AS

### 4. Fusion des sources (Optionnel)

Jointure du dataset principal avec les données géographiques secondaires sur la colonne `origin`.

In [5]:
# Fusion du dataset principal avec les informations géographiques
df_merged = pd.merge(df_main, origin_info, on='origin', how='left')

print(f"Dimensions après fusion : {df_merged.shape}")
df_merged.head()

Dimensions après fusion : (398, 11)

,name,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,region,continent_code
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,3504,12.0,70,usa,Amérique du Nord,NA
1,buick skylark 320,15.0,8,350.0,165.0,3693,11.5,70,usa,Amérique du Nord,NA
2,plymouth satellite,18.0,8,318.0,150.0,3436,11.0,70,usa,Amérique du Nord,NA
3,amc rebel sst,16.0,8,304.0,150.0,3433,12.0,70,usa,Amérique du Nord,NA
4,ford torino,17.0,8,302.0,140.0,3449,10.5,70,usa,Amérique du Nord,NA

### 5. Consignation des données d'entrée brutes

Sauvegardez l'état brut de vos données d'entrée pour la suite du pipeline.

In [6]:
# Sauvegarde du dataset fusionné
output_path = '../data/raw/Automobile_merged.csv'
df_merged.to_csv(output_path, index=False)

print(f"Dataset fusionné sauvegardé : {output_path}")
print(f"Dimensions finales : {df_merged.shape}")
print("Acquisition terminée avec succès !")

Dataset fusionné sauvegardé : ../data/raw/Automobile_merged.csv
Dimensions finales : (398, 11)
Acquisition terminée avec succès !